# Generated by Django 6.0.5 on 2026-07-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
        ('tickets', '0002_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closing_commit_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Hash du commit de clôture'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closing_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositories.repository', verbose_name='Dépôt de clôture'),
        ),
    ]
