# Generated by Django 6.0.5 on 2026-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_closing_commit_hash_ticket_closing_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('a_clore', 'À clore'), ('cloture', 'Clôturé')], default='nouveau', max_length=20, verbose_name='Statut'),
        ),
    ]
