# Generated by Django 6.0.6 on 2026-07-02 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tickets', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('version', models.CharField(help_text='ex: 1.0.0', max_length=50, verbose_name='Version')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('is_released', models.BooleanField(default=False, verbose_name='Publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='projects.project')),
                ('tickets', models.ManyToManyField(blank=True, related_name='releases', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
    ]
