# Generated by Django 6.0.6 on 2026-06-30 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('budget_type', models.CharField(choices=[('investment', 'Investissement'), ('fonctionnement', 'Fonctionnement')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant alloué')),
            ],
            options={
                'verbose_name': 'Budget annuel',
                'verbose_name_plural': 'Budgets annuels',
                'ordering': ['-year', 'budget_type'],
                'unique_together': {('year', 'budget_type')},
            },
        ),
    ]
