# Generated by Django 6.0.6 on 2026-06-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='LDAP activé')),
                ('server_uri', models.CharField(blank=True, max_length=500, verbose_name='URI serveur LDAP')),
                ('bind_dn', models.CharField(blank=True, max_length=500, verbose_name='DN de liaison')),
                ('bind_password', models.CharField(blank=True, max_length=500, verbose_name='Mot de passe liaison')),
                ('base_dn', models.CharField(blank=True, max_length=500, verbose_name='DN base')),
                ('user_filter', models.CharField(blank=True, default='(uid=%(user)s)', max_length=500, verbose_name='Filtre utilisateur')),
                ('attribute_username', models.CharField(default='uid', max_length=100, verbose_name='Attribut username')),
                ('attribute_email', models.CharField(default='mail', max_length=100, verbose_name='Attribut email')),
                ('attribute_fullname', models.CharField(default='cn', max_length=100, verbose_name='Attribut nom complet')),
            ],
            options={
                'verbose_name': 'Configuration LDAP',
                'verbose_name_plural': 'Configuration LDAP',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ldap_dn',
            field=models.CharField(blank=True, max_length=512, verbose_name='DN LDAP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Création 2FA'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA activé'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='Code 2FA'),
        ),
    ]
