# Generated by Django 6.0.5 on 2026-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guichet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guichetticket',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('en_etude', 'En étude'), ('resolu', 'Résolu'), ('valide', 'Validé'), ('realise', 'Réalisé'), ('ferme', 'Fermé')], default='nouveau', max_length=20, verbose_name='Statut'),
        ),
    ]
