# Generated by Django 6.0.6 on 2026-06-30 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Refusé')], default='draft', max_length=20, verbose_name='Statut')),
                ('sequence_number', models.IntegerField(editable=False, verbose_name='Numéro séquence')),
                ('year', models.IntegerField(editable=False, verbose_name='Année')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Date création')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('provider_contact_name', models.CharField(max_length=255, verbose_name='Nom du contact')),
                ('provider_contact_email', models.EmailField(max_length=254, verbose_name='Email du contact')),
                ('provider_contact_phone', models.CharField(max_length=50, verbose_name='Téléphone du contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='providers.provider', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'DAT',
                'verbose_name_plural': 'DAT',
                'ordering': ['-year', '-sequence_number'],
                'unique_together': {('sequence_number', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DATLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produit')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Référence')),
                ('unit', models.CharField(choices=[('U', 'Unité'), ('D', 'Jour')], default='U', max_length=1, verbose_name='Unité')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('global_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total')),
                ('budget_type', models.CharField(choices=[('investment', 'Investissement'), ('fonctionnement', 'Fonctionnement')], max_length=20, verbose_name='Type budget')),
                ('budget_category', models.CharField(choices=[('licences', 'Licences'), ('maintenance', 'Maintenance'), ('pc', 'PC'), ('servers', 'Serveurs'), ('network', 'Réseau'), ('security', 'Sécurité'), ('consulting', 'Conseil')], max_length=20, verbose_name='Catégorie')),
                ('dat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dat.dat', verbose_name='DAT')),
            ],
            options={
                'verbose_name': 'Ligne DAT',
                'verbose_name_plural': 'Lignes DAT',
                'ordering': ['id'],
            },
        ),
    ]
