# Generated by Django 6.0.6 on 2026-07-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DATTtemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('lines', models.JSONField(blank=True, default=list, verbose_name='Lignes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Modèle de DAT',
                'verbose_name_plural': 'Modèles de DAT',
                'ordering': ['name'],
            },
        ),
    ]
