# Generated by Django 6.0.5 on 2026-07-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.deal', verbose_name='Affaire CRM'),
        ),
    ]
