# Generated by Django 6.0.5 on 2026-07-02 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_add_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1ʳᵉ relance'), (2, '2ᵉ relance'), (3, '3ᵉ relance')], default=1, verbose_name='Niveau')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant dû')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='erp.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Relance',
                'verbose_name_plural': 'Relances',
                'ordering': ['-date'],
            },
        ),
    ]
