# Generated by Django 6.0.5 on 2026-07-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_add_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='Modèle')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Représentation')),
                ('action', models.CharField(choices=[('create', 'Création'), ('edit', 'Modification'), ('delete', 'Suppression'), ('convert', 'Conversion devis→facture'), ('payment', 'Paiement'), ('reminder', 'Relance'), ('export', 'Export')], max_length=20, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit ERP",
                'verbose_name_plural': "Journaux d'audit ERP",
                'ordering': ['-created_at'],
            },
        ),
    ]
