# Generated by Django 6.0.6 on 2026-07-02 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_attachment'),
        ('erp', '0005_add_erp_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('lines', models.JSONField(blank=True, default=list, verbose_name='Lignes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de devis',
                'verbose_name_plural': 'Modèles de devis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('lines', models.JSONField(blank=True, default=list, verbose_name='Lignes')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('yearly', 'Annuelle')], default='monthly', max_length=20, verbose_name='Fréquence')),
                ('next_date', models.DateField(verbose_name='Prochaine échéance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='crm.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture récurrente',
                'verbose_name_plural': 'Factures récurrentes',
                'ordering': ['next_date'],
            },
        ),
    ]
