# Generated by Django 6.0.5 on 2026-07-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['order', 'deadline'], 'verbose_name': 'Tâche', 'verbose_name_plural': 'Tâches'},
        ),
    ]
