# Generated by Django 6.0.6 on 2026-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Cyonima-ES-Tools', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Recommandé 120x40 px, PNG/SVG', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
