# Generated by Django 6.0.6 on 2026-07-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hsts_seconds',
            field=models.PositiveIntegerField(default=31536000, help_text='0 = désactivé. Défaut : 31536000 (1 an)', verbose_name='Durée HSTS (secondes)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='https_enabled',
            field=models.BooleanField(default=False, verbose_name='HTTPS activé'),
        ),
    ]
