# Generated by Django 6.0.6 on 2026-07-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_hsts_seconds_siteconfig_https_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ssl_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ssl/', verbose_name='Certificat SSL (.crt/.pem)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ssl_private_key',
            field=models.FileField(blank=True, null=True, upload_to='ssl/', verbose_name='Clé privée (.key)'),
        ),
    ]
