# Generated by Django 6.0.6 on 2026-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_com', '0002_comarticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comarticle',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
    ]
