# Generated by Django 6.0.6 on 2026-07-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_com', '0003_alter_comarticle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comarticle',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='publie', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='comarticle',
            name='tags',
            field=models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500, verbose_name='Tags'),
        ),
    ]
