# Generated by Django 6.0.6 on 2026-06-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='projects.project')),
            ],
            options={
                'verbose_name': 'Campagne de test',
                'verbose_name_plural': 'Campagnes de test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(editable=False, verbose_name='Numéro')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('execution_conditions', models.TextField(blank=True, verbose_name="Conditions d'exécution")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scenarios', to='projects.project')),
                ('requirements', models.ManyToManyField(blank=True, related_name='test_scenarios', to='requirements.requirement')),
            ],
            options={
                'verbose_name': 'Scénario de test',
                'verbose_name_plural': 'Scénarios de test',
                'ordering': ['number'],
                'unique_together': {('project', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tests/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tests.testscenario')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='CampaignTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('en_cours', 'En cours'), ('verifie', 'Vérifié'), ('valide', 'Validé')], default='backlog', max_length=20, verbose_name='Statut')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.testcampaign')),
                ('test_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testscenario')),
            ],
            options={
                'verbose_name': 'Test de campagne',
                'verbose_name_plural': 'Tests de campagne',
                'ordering': ['position'],
                'unique_together': {('campaign', 'test_scenario')},
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='N° étape')),
                ('action', models.TextField(verbose_name='Action')),
                ('expected_result', models.TextField(verbose_name='Résultat attendu')),
                ('test_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tests.testscenario')),
            ],
            options={
                'verbose_name': 'Étape de test',
                'verbose_name_plural': 'Étapes de test',
                'ordering': ['step_number'],
                'unique_together': {('test_scenario', 'step_number')},
            },
        ),
    ]
