# Generated by Django 6.0.5 on 2026-07-02 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('reussi', 'Réussi'), ('en_echec', 'En échec'), ('bloque', 'Bloqué'), ('non_execute', 'Non exécuté')], default='non_execute', max_length=20, verbose_name='Résultat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('step_results', models.JSONField(blank=True, default=dict, verbose_name='Résultats par étape')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tests.testscenario')),
            ],
            options={
                'verbose_name': 'Exécution de test',
                'verbose_name_plural': 'Exécutions de test',
                'ordering': ['-executed_at'],
            },
        ),
    ]
