# Generated by Django 6.0.6 on 2026-07-22 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_add_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invité le')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activé le')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_user', to='crm.contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur portail',
                'verbose_name_plural': 'Utilisateurs portail',
            },
        ),
    ]
