# Generated by Django 6.0.5 on 2026-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmtask',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rappel'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Rappel envoyé'),
        ),
    ]
