# Generated by Django 6.0.5 on 2026-07-01 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_reminder_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=20, verbose_name='Étape précédente')),
                ('to_stage', models.CharField(max_length=20, verbose_name='Nouvelle étape')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='crm.deal')),
            ],
            options={
                'verbose_name': "Historique d'étape",
                'verbose_name_plural': 'Historique des étapes',
                'ordering': ['-changed_at'],
            },
        ),
    ]
