# Generated by Django 6.0.6 on 2026-06-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(blank=True, help_text='Pour les prestataires externes', max_length=255, verbose_name="Société d'origine"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('mission', 'Mission'), ('stage', 'Stage'), ('alternance', 'Alternance'), ('freelance', 'Freelance'), ('interim', 'Intérim')], max_length=20, verbose_name='Type'),
        ),
    ]
