# Generated by Django 6.0.5 on 2026-07-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_company_alter_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bepc', 'BEPC'), ('bep', 'BEP'), ('cap', 'CAP'), ('bac', 'BAC'), ('bac+2', 'BAC+2'), ('bac+3', 'BAC+3'), ('bac+5', 'BAC+5'), ('doctorat', 'Doctorat')], max_length=20, verbose_name='Niveau')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du diplôme')),
                ('school', models.CharField(max_length=255, verbose_name='Établissement')),
                ('year', models.PositiveIntegerField(verbose_name="Année d'obtention")),
                ('file', models.FileField(blank=True, null=True, upload_to='hr/diplomas/', verbose_name='Copie du diplôme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='hr.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'ordering': ['-year', 'name'],
            },
        ),
    ]
