# Generated by Django 6.0.5 on 2026-07-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_add_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la formation')),
                ('organization', models.CharField(max_length=255, verbose_name='Organisme de formation')),
                ('year', models.PositiveIntegerField(verbose_name='Année de réalisation')),
                ('file', models.FileField(blank=True, null=True, upload_to='hr/trainings/', verbose_name='Attestation de formation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='hr.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-year', 'name'],
            },
        ),
    ]
