# Generated by Django 6.0.5 on 2026-07-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_add_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Titre du poste')),
                ('employer', models.CharField(max_length=255, verbose_name='Employeur')),
                ('description', models.TextField(blank=True, verbose_name='Description des fonctions')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='hr.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Emploi précédent',
                'verbose_name_plural': 'Emplois précédents',
                'ordering': ['-start_date'],
            },
        ),
    ]
