# Generated by Django 6.0.5 on 2026-07-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_add_employment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hr/cvs/', verbose_name='CV')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='hr.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
