# Generated by Django 6.0.5 on 2026-07-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_add_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B3', 'B3'), ('B4', 'B4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('D8', 'D8'), ('E9', 'E9'), ('E10', 'E10'), ('F11', 'F11'), ('F12', 'F12'), ('G13', 'G13'), ('G14', 'G14'), ('H15', 'H15'), ('H16', 'H16'), ('I17', 'I17'), ('I18', 'I18')], max_length=4, verbose_name='Grade (Ccn. Métallurgie)'),
        ),
    ]
