# Generated by Django 6.0.6 on 2026-06-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Image à la une'),
        ),
    ]
