from django.urls import path
from . import views

urlpatterns = [
    path('', views.document_list, name='ged_document_list'),
    path('<int:pk>/', views.document_detail, name='ged_document_detail'),
    path('<int:pk>/telecharger/', views.document_download, name='ged_document_download'),
    path('ajouter/', views.document_create, name='ged_document_create'),
    path('<int:pk>/modifier/', views.document_edit, name='ged_document_edit'),
    path('<int:pk>/supprimer/', views.document_delete, name='ged_document_delete'),
    path('categories/', views.category_list, name='ged_category_list'),
    path('categories/ajouter/', views.category_create, name='ged_category_create'),
    path('categories/<int:pk>/modifier/', views.category_edit, name='ged_category_edit'),
    path('categories/<int:pk>/supprimer/', views.category_delete, name='ged_category_delete'),
    path('versions/<int:pk>/restaurer/', views.version_restore, name='ged_version_restore'),
    path('<int:pk>/soumettre/', views.document_submit, name='ged_document_submit'),
    path('<int:pk>/approuver/', views.document_approve, name='ged_document_approve'),
    path('<int:pk>/archiver/', views.document_archive, name='ged_document_archive'),
    path('<int:pk>/desarchiver/', views.document_unarchive, name='ged_document_unarchive'),
    path('<int:pk>/partager/', views.document_share, name='ged_document_share'),
    path('partage/<uuid:token>/', views.shared_document, name='ged_shared_document'),
    path('liens/<int:pk>/supprimer/', views.delete_shared_link, name='ged_delete_shared_link'),
    path('<int:pk>/favori/', views.toggle_favorite, name='ged_toggle_favorite'),
    path('categorie/<int:cat_pk>/abonner/', views.toggle_subscription, name='ged_toggle_subscription'),
    path('mes-favoris/', views.favorites_list, name='ged_favorites_list'),
    path('corbeille/', views.trash_list, name='ged_trash_list'),
    path('<int:pk>/restaurer/', views.document_restore, name='ged_document_restore'),
    path('<int:pk>/supprimer-definitivement/', views.document_permanent_delete, name='ged_document_permanent_delete'),
    path('rapport-audit/', views.audit_report, name='ged_audit_report'),
]
