# Generated by Django 6.0.5 on 2026-07-02 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('status_change', 'Changement de statut'), ('assign', 'Assignation'), ('comment', 'Commentaire')], max_length=30, verbose_name='Action')),
                ('entity_type', models.CharField(max_length=50, verbose_name="Type d'entité")),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID entité')),
                ('summary', models.CharField(max_length=255, verbose_name='Résumé')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alm_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de modification',
                'verbose_name_plural': 'Journal des modifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
