from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='erp_dashboard'),
    path('devis/', views.quotation_list, name='erp_quotation_list'),
    path('devis/creer/', views.quotation_create, name='erp_quotation_create'),
    path('devis/<int:pk>/', views.quotation_detail, name='erp_quotation_detail'),
    path('devis/<int:pk>/modifier/', views.quotation_edit, name='erp_quotation_edit'),
    path('devis/<int:pk>/supprimer/', views.quotation_delete, name='erp_quotation_delete'),
    path('devis/<int:pk>/convertir/', views.quotation_convert, name='erp_quotation_convert'),
    path('factures/', views.invoice_list, name='erp_invoice_list'),
    path('factures/creer/', views.invoice_create, name='erp_invoice_create'),
    path('factures/<int:pk>/', views.invoice_detail, name='erp_invoice_detail'),
    path('factures/<int:pk>/modifier/', views.invoice_edit, name='erp_invoice_edit'),
    path('factures/<int:pk>/supprimer/', views.invoice_delete, name='erp_invoice_delete'),
    path('avoirs/', views.creditnote_list, name='erp_creditnote_list'),
    path('avoirs/creer/', views.creditnote_create, name='erp_creditnote_create'),
    path('avoirs/<int:pk>/supprimer/', views.creditnote_delete, name='erp_creditnote_delete'),
    path('factures-fournisseurs/', views.supplier_invoice_list, name='erp_supplier_invoice_list'),
    path('factures-fournisseurs/creer/', views.supplier_invoice_create, name='erp_supplier_invoice_create'),
    path('factures-fournisseurs/<int:pk>/modifier/', views.supplier_invoice_edit, name='erp_supplier_invoice_edit'),
    path('factures-fournisseurs/<int:pk>/supprimer/', views.supplier_invoice_delete, name='erp_supplier_invoice_delete'),
    path('paiements/creer/', views.payment_create, name='erp_payment_create'),
    path('devis/<int:pk>/pdf/', views.quotation_pdf, name='erp_quotation_pdf'),
    path('factures/<int:pk>/pdf/', views.invoice_pdf, name='erp_invoice_pdf'),
    path('exporter/devis/', views.export_quotations_csv, name='erp_export_quotations_csv'),
    path('exporter/factures/', views.export_invoices_csv, name='erp_export_invoices_csv'),
    path('exporter/avoirs/', views.export_creditnotes_csv, name='erp_export_creditnotes_csv'),
    path('exporter/factures-fournisseurs/', views.export_supplier_invoices_csv, name='erp_export_supplier_invoices_csv'),
    path('produits/', views.product_list, name='erp_product_list'),
    path('produits/creer/', views.product_create, name='erp_product_create'),
    path('produits/<int:pk>/modifier/', views.product_edit, name='erp_product_edit'),
    path('produits/<int:pk>/supprimer/', views.product_delete, name='erp_product_delete'),
    path('tva/', views.tva_report, name='erp_tva_report'),
    path('relances/', views.reminder_list, name='erp_reminder_list'),
    path('relances/<int:pk>/creer/', views.reminder_create, name='erp_reminder_create'),
    path('relances/<int:pk>/', views.reminder_detail, name='erp_reminder_detail'),
    path('relances/<int:pk>/pdf/', views.reminder_pdf, name='erp_reminder_pdf'),
    path('audit/', views.audit_log_list, name='erp_audit_log'),
    path('factures-recurrentes/', views.recurring_list, name='erp_recurring_list'),
    path('factures-recurrentes/creer/', views.recurring_create, name='erp_recurring_create'),
    path('modele-devis/sauvegarder/', views.quotation_template_save, name='erp_template_save'),
    path('rapprochement/', views.reconciliation, name='erp_reconciliation'),
]
