# Generated by Django 6.0.6 on 2026-06-30 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComexMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message COMEX',
                'verbose_name_plural': 'Messages COMEX',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComexAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comex/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='comex_forum.comexmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ComexThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(editable=False)),
                ('sequence_number', models.IntegerField(editable=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comex_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fil COMEX',
                'verbose_name_plural': 'Fils COMEX',
                'ordering': ['-year', '-sequence_number'],
                'unique_together': {('year', 'sequence_number')},
            },
        ),
        migrations.AddField(
            model_name='comexmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comex_forum.comexthread'),
        ),
    ]
