# Generated by Django 6.0.6 on 2026-06-30 22:36

import apps.ged.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('color', models.CharField(default='#1a3a6b', help_text='Hex (#1a3a6b)', max_length=7, verbose_name='Couleur')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to=apps.ged.models.document_upload_path, verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500, verbose_name='Tags')),
                ('file_size', models.BigIntegerField(default=0, editable=False, verbose_name='Taille (octets)')),
                ('file_type', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Type')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ged.documentcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
    ]
