# Generated by Django 6.0.6 on 2026-06-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='registration_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='N° enregistrement'),
        ),
    ]
