# Generated by Django 6.0.5 on 2026-07-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0003_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ged/versions/%Y/%m/', verbose_name='Fichier')),
                ('version_number', models.CharField(max_length=20, verbose_name='Version')),
                ('file_size', models.BigIntegerField(default=0, editable=False, verbose_name='Taille (octets)')),
                ('file_type', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Type')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ged.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
