# Generated by Django 6.0.5 on 2026-07-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0005_add_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_text',
            field=models.TextField(blank=True, editable=False, verbose_name='Texte extrait'),
        ),
    ]
