# Generated by Django 6.0.5 on 2026-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0008_add_favorites_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le'),
        ),
    ]
