# Generated by Django 6.0.6 on 2026-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0010_add_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
    ]
