# Generated by Django 6.0.6 on 2026-06-30 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-app')], default='in_app', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_dat_creation', models.BooleanField(default=True, verbose_name='Email création DAT')),
                ('email_ticket_change', models.BooleanField(default=True, verbose_name='Email changement ticket')),
                ('email_report_ready', models.BooleanField(default=True, verbose_name='Email rapport disponible')),
                ('digest_daily', models.BooleanField(default=False, verbose_name='Résumé quotidien')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence notification',
                'verbose_name_plural': 'Préférences notifications',
            },
        ),
    ]
