# Generated by Django 6.0.5 on 2026-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='email_erp_notification',
            field=models.BooleanField(default=True, verbose_name='Email notification ERP'),
        ),
    ]
