from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='hr_dashboard'),
    path('employes/', views.employee_list, name='hr_employee_list'),
    path('employes/creer/', views.employee_create, name='hr_employee_create'),
    path('employes/<int:pk>/', views.employee_detail, name='hr_employee_detail'),
    path('employes/<int:pk>/modifier/', views.employee_edit, name='hr_employee_edit'),
    path('employes/<int:pk>/supprimer/', views.employee_delete, name='hr_employee_delete'),
    path('departements/', views.department_list, name='hr_department_list'),
    path('departements/creer/', views.department_create, name='hr_department_create'),
    path('departements/<int:pk>/modifier/', views.department_edit, name='hr_department_edit'),
    path('departements/<int:pk>/supprimer/', views.department_delete, name='hr_department_delete'),
    path('contrats/', views.contract_list, name='hr_contract_list'),
    path('contrats/creer/', views.contract_create, name='hr_contract_create'),
    path('contrats/<int:pk>/modifier/', views.contract_edit, name='hr_contract_edit'),
    path('contrats/<int:pk>/supprimer/', views.contract_delete, name='hr_contract_delete'),
    path('conges/', views.leave_list, name='hr_leave_list'),
    path('conges/creer/', views.leave_create, name='hr_leave_create'),
    path('conges/<int:pk>/modifier/', views.leave_edit, name='hr_leave_edit'),
    path('conges/<int:pk>/supprimer/', views.leave_delete, name='hr_leave_delete'),
    path('conges/<int:pk>/valider/', views.leave_approve, name='hr_leave_approve'),
    path('conges/<int:pk>/refuser/', views.leave_reject, name='hr_leave_reject'),
    path('profil/', views.profil, name='hr_profil'),
    path('profil/diplomes/ajouter/', views.diplome_create, name='hr_diplome_create'),
    path('profil/diplomes/<int:pk>/modifier/', views.diplome_edit, name='hr_diplome_edit'),
    path('profil/diplomes/<int:pk>/supprimer/', views.diplome_delete, name='hr_diplome_delete'),
    path('profil/certifications/ajouter/', views.certification_create, name='hr_certification_create'),
    path('profil/certifications/<int:pk>/modifier/', views.certification_edit, name='hr_certification_edit'),
    path('profil/certifications/<int:pk>/supprimer/', views.certification_delete, name='hr_certification_delete'),
    path('profil/formations/ajouter/', views.training_create, name='hr_training_create'),
    path('profil/formations/<int:pk>/modifier/', views.training_edit, name='hr_training_edit'),
    path('profil/formations/<int:pk>/supprimer/', views.training_delete, name='hr_training_delete'),
    path('profil/emplois/ajouter/', views.employment_create, name='hr_employment_create'),
    path('profil/emplois/<int:pk>/modifier/', views.employment_edit, name='hr_employment_edit'),
    path('profil/emplois/<int:pk>/supprimer/', views.employment_delete, name='hr_employment_delete'),
    path('profil/cvs/ajouter/', views.cv_upload, name='hr_cv_upload'),
    path('profil/cvs/<int:pk>/supprimer/', views.cv_delete, name='hr_cv_delete'),
    path('profil/cvs/<int:pk>/voir/', views.cv_serve, name='hr_cv_serve'),
    path('employes/<int:employee_pk>/evaluations/ajouter/', views.evaluation_create, name='hr_evaluation_create'),
    path('evaluations/<int:pk>/modifier/', views.evaluation_edit, name='hr_evaluation_edit'),
    path('evaluations/<int:pk>/supprimer/', views.evaluation_delete, name='hr_evaluation_delete'),
]
